### ISSUE TITLE
minitar needs to convert archive pathnames

### ISSUE THREAD

**Issue by eschaton** [quicklisp/quicklisp-bootstrap#17]
With only a little bit of hacking, I managed to load the QuickLisp bootstrap on MCL 5.1 on Mac OS 9.2.2. However during the installation the tar file was expanded into a flat directory of files with slashes in their names.

This is probably because the classic Mac OS uses colon as its path separator, while minitar is expecting to be able to use a slash-containing path obtained from a tar file directly in a filesystem path.

**Comment by quicklisp** [comment]
At this time, I am going to stick to supporting Lisps that can handle Unix-style pathname strings.

I'm concerned about the clutter introduced by supporting niche filesystems in this regard.
