### ISSUE TITLE
Compatibility with elisp?

### ISSUE THREAD

**Issue by Kreyren** [quicklisp/quicklisp-bootstrap#21]
### Context
Researching for https://github.com/Kreyren/kreyren/issues/47 to allow quicklisp implementation in cargo-make.

### Issue
Currently loading quicklisp through emacs to interpret the following file returns `Symbol’s function definition is void: defpackage`.

```lisp
;; Not working on elisp
(setf *load-verbose* nil)

(load "/home/kreyren/quicklisp/setup.lisp" :verbose nil)

(ql:quickload :uiop :silent t)

(write-line (uiop:getenv "MESSAGE"))
```

### Question
Is it possible to optimize quicklisp to allow it to be ran through emacs?

**Comment by Kreyren** [comment]
CC @xach

**Comment by Kreyren** [comment]
Apparently quicklisp depends on ASDF, which heavily uses CLOS so porting it to other lisp dialects would be pain to do? Or is it practical to do so?

**Comment by xach** [comment]
I don’t see any path to it happening. Common Lisp and elisp are completely different Lisp systems.

**Comment by Kreyren** [comment]
thanks for info
