### ISSUE TITLE
Setting up quicklisp without interactive input

### ISSUE THREAD

**Issue by jwg4** [quicklisp/quicklisp-bootstrap#23]
Hi there, I am using sbcl and would like to run the quicklisp setup using the instructions on the quicklisp site https://www.quicklisp.org/beta/#installation or the very similar ones here: https://lisp-lang.org/learn/getting-started/

However, I'd like to be able to do this using a script which runs automatically on a test machine where there is no possibility for interactive input to the script. 

This fails because ql:add-to-init-file waits for 'Enter' to go ahead and write to the sbcl config file.

Is there some way I can workaround this currently? If not, could the function be changed so that optionally it doesn't need Enter?

**Comment by quicklisp** [comment]
See `without-prompting` and `*do-not-prompt*` for options to control
prompting behavior.

You also need not use `ql:add-to-init-file`. It's not a mandatory part of
the installation.

**Comment by jwg4** [comment]
Worked, thank you very much for the speedy and helpful reply!
